// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cybqfnirsyynolgqfgkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5YnFmbmlyc3l5bm9sZ3FmZ2tkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3OTc0MjMsImV4cCI6MjA1MzM3MzQyM30.TL_EdRmTkKXtPztKIeAlb2yGWzOd1rVBsviWje9GXf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);